name: Maven Package
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }}/ApiMasterPCBuilder # location for the settings.xml file

    - name: Build with Maven
      run: mvn -B clean package --file ApiMasterPCBuilder/pom.xml

    - name: subir fichero
      uses: actions/upload-artifact@v4
      with:
        name: allartifacts
        path: ApiMasterPCBuilder/target/*

    - name: Download artifact
      uses: actions/download-artifact@v4
      with:
        name: allartifacts
        path: distfiles


    #- name: Build Docker image
    #  run: |
    #    docker build -t helloapp .
   
    - name: Upload to remote with SCP
      uses: appleboy/scp-action@v0.1.7
      with:
        username: root
        host: "146.190.12.221"
        key: "ji8VqvweXT0rwLEBDZ$Q"
        source: "ApiMasterPCBuilder/target/*.jar"
        target: "~/"
        overwrite: true

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Deploy to digitalocean
      uses: appleboy/ssh-action@master
      with:
        username: carlos
        host: "appsiespuerto.myvnc.com"
        key: ${{ secrets.SSH_KEY }}
        script: |
            docker stop carlos-web-1 ; 
            docker rm carlos-web-1 -f ; 
            docker rmi carlos-web -f ; 
            docker compose up -d
