name: Maven Package

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      mongo:
        image: mongo:latest
        ports:
          - 27017:27017
        options: > 
          --health-cmd="mongo --eval 'db.runCommand(\"ping\").ok'" 
          --health-interval=10s 
          --health-timeout=5s 
          --health-retries=5

    steps:
    - uses: actions/checkout@v3

    - name: Set timezone
      run: sudo timedatectl set-timezone Europe/Madrid

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        server-id: github
        settings-path: ${{ github.workspace }}/ApiMasterPCBuilder

    - name: Cache Maven packages
      uses: actions/cache@v2
      with:
        path: ~/.m2
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-maven

    - name: Build with Maven
      run: mvn -B clean package --file ApiMasterPCBuilder/pom.xml

    - name: Run tests with detailed logging
      run: mvn test -X --file ApiMasterPCBuilder/pom.xml

    - name: Upload to remote with SCP
      uses: appleboy/scp-action@v0.1.7
      with:
        username: root
        host: "146.190.2.205"
        password: "fz2EfMkU^Fbb<P3ETrh"
        source: "ApiMasterPCBuilder/target/*.jar"
        target: "~/"
        overwrite: true

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Deploy to digitalocean
      uses: appleboy/ssh-action@master
      with:
        username: root
        host: "146.190.2.205"
        password: "fz2EfMkU^Fbb<P3ETrh"
        script: |
          docker stop root_MasterPcBuildercontainer_1 || true; 
          docker rm root_MasterPcBuildercontainer_1 -f || true; 
          docker rmi masterpcbuilder -f || true; 
          docker build -t masterpcbuilder .;
          docker-compose build;
          docker-compose up -d
